---
title: "Mephyston Study areas"
format: dashboard
editor_options: 
  chunk_output_type: console
---


```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(sf)
library(leaflet)
library(leaflet.extras)
```

```{r}
v <- st_read("data/geoinfo/guadarrama_dec_bbox.shp", quiet=TRUE)
valdemaqueda <- v |> filter(site == "valdemaqueda")
valsain <- v |> filter(str_detect(site, "valsain"))
```

```{r}
### Valdemaqueda 

pies_valdemaqueda_csv <- read_delim("data/geoinfo/gps_pies_valdemaqueda_decaimiento.csv", delim = ";")
pies_valdemaqueda <- st_as_sf(pies_valdemaqueda_csv, coords = c("lon", "lat")) |> 
  mutate(sp = case_when(
    tipo == "enebro" ~ "Juniperus",
    str_detect(tipo, "pinaster") ~ "Pinus pinaster", 
    str_detect(tipo, "pinea") ~ "Pinus pinea",
    tipo == "encina" ~ "Quercus ilex"
  )) |> 
  mutate(status = case_when(
    str_detect(tipo, "decaimiento") ~ "Decaimiento",
    str_detect(tipo, "contro") ~ "Sanos") 
  )

st_crs(pies_valdemaqueda) <- 4326

pinaster_valdemaqueda <- pies_valdemaqueda |> 
  filter(sp == "Pinus pinaster") |> 
  mutate(name = case_when(
    status == "Decaimiento" ~ paste0("M", sprintf("%02d", numero)), 
    status == "Sanos" ~ paste0("S", sprintf("%02d", numero))
  ))

pinea_valdemaqueda <- pies_valdemaqueda |> 
  filter(sp == "Pinus pinea") |> 
  mutate(status = ifelse(is.na(status), "Sanos", status))
```


```{r}
geo_valsain <- read_delim("data/geoinfo/gps_pies_valsain.csv", delim = ";")

pies_valsain_old <- st_as_sf((geo_valsain |> filter(tipo == "tree")), 
                         coords = c("lon", "lat"), crs = st_crs(4326))

geo_valsain_sanos<- read_delim("data/geoinfo/gps_valsain_sylvestris_sanos.csv") |>
  st_as_sf(coords = c("X", "Y"), crs = st_crs(4326))

meteo_valsain <-  st_as_sf((geo_valsain |> filter(tipo == "meteo")), 
                         coords = c("lon", "lat"), crs = st_crs(4326)) |> 
  mutate(subtype = case_when(
    name == "EstacionMeteo" ~ "Soil Temp", 
    TRUE ~ "Weather Station"
  ))

```

```{r}
#| echo: false
#| message: false
#| warning: false

w <- bind_rows(
  (pies_valsain_old |> 
  filter(tipo == "tree") |> 
  mutate(sp = "Pinus sylvestris") |> 
  rename(numero = ID, status = parcela) |> 
  dplyr::select(-time)), 
  (geo_valsain_sanos),
  (pinaster_valdemaqueda))

st_write(w, "data/geoinfo/pies_pinaster_sylvestris_guadarrama.shp", append = FALSE, quiet = TRUE)

pies_valsain <- w |> filter(sp == "Pinus sylvestris")
```



```{r}
l8 <- st_read("data/geoinfo/grid/l8.shp", quiet=TRUE)
s2 <- st_read("data/geoinfo/grid/s2.shp", quiet=TRUE)
mod13 <- st_read("data/geoinfo/grid/mod13.shp", quiet=TRUE)
```


```{r}
maxzoom <- 30

mymap <- leaflet(options = leafletOptions(maxZoom = maxzoom)) |>
  addProviderTiles("Esri.WorldImagery", group = "Satellite") |> 
  addWMSTiles("http://www.ign.es/wms-inspire/pnoa-ma",
    layers = "OI.OrthoimageCoverage",
    group = "PNOA Máxima Actualidad",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE,
      maxZoom = maxzoom),
    attribution = 'PNOA cedido por © <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
  ) |> 
  addWMSTiles("https://www.ign.es/wms/pnoa-historico?",
    layers = "AMS_1956-1957",
    group = "Vuelo Americano (Serie B, 1956-1957)",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE,
      maxZoom = maxzoom),
    attribution = 'PNOA cedido por © <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
  ) |> 
  addWMSTiles("https://www.ign.es/wms/pnoa-historico?",
    layers = "Interministerial_1973-1986",
    group = "Interministerial 1973 - 1986",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE,
      maxZoom = maxzoom),
    attribution = 'PNOA cedido por © <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
  ) |> 
  addPolygons(data = l8,
              group= 'Landsat Grid',
              fillOpacity = 0, 
              color = "black",
              stroke = TRUE,
              weight = 0.7) |> 
  addPolygons(data = s2,
              group= 'Sentinel Grid',
              fillOpacity = 0, 
              color = "blue",
              stroke = TRUE,
              weight = 0.7) |> 
  addPolygons(data = mod13,
              group= 'MOD13Q Grid',
              fillOpacity = 0, 
              color = "white",
              stroke = TRUE,
              weight = 0.7) 
```



# Valsaín

```{r}

colores_parcela <- awesomeIconList(
  "Decaimiento" = makeAwesomeIcon(
    icon = "tree",
    markerColor = "red",
    library = "fa"
  ),
  "Sanos" = makeAwesomeIcon(
    icon = "tree",
    markerColor = "green",
    library = "fa"
  ))

colores_meteo <- awesomeIconList(
  "Soil Temp" = makeAwesomeIcon(
    icon = "temperature-half",
    markerColor = "blue",
    library = "fa"
  ),
  "Weather Station" = makeAwesomeIcon(
    icon = "tower-broadcast",
    markerColor = "white",
    library = "fa"
  ))


myext <- st_bbox(valsain) |> as.vector()

mymap |> 
  fitBounds(myext[1], myext[2], myext[3], myext[4]) |> 
  addPolygons(data = valsain,
              group= 'Valsain',
              fillOpacity = 0, 
              color = "red",
              stroke = TRUE) |> 
  addAwesomeMarkers(data = pies_valsain, 
                    group = "Árboles",
                    label = ~name, 
                    icon = ~ colores_parcela[status]) |> 
  addAwesomeMarkers(data = meteo_valsain, 
                    group = "Climate Stations",
                    label = ~name, 
                    icon = ~colores_meteo[subtype]) |> 
  addLayersControl(
    position = "bottomright",
    baseGroups = c("Basemap", "PNOA Máxima Actualidad", 
                  "Interministerial 1973 - 1986", "Vuelo Americano (Serie B, 1956-1957)"),
    overlayGroups = c("Árboles","Climate Stations", "Valsain", "MOD13Q Grid", "Landsat Grid", "Sentinel Grid"), 
    options = layersControlOptions(collapsed = TRUE)
  ) |> 
  hideGroup("Landsat Grid") |> 
  hideGroup("Sentinel Grid") |> 
  hideGroup("MOD13Q Grid")
  
```


# Valdemaqueda
```{r}
myext <- st_bbox(valdemaqueda) |> as.vector()

mymap |> 
  fitBounds(myext[1], myext[2], myext[3], myext[4]) |> 
  addPolygons(data = valdemaqueda,
              group= 'Valdemaqueda',
              fillOpacity = 0, 
              color = "red",
              stroke = TRUE) |>
    addAwesomeMarkers(data = pinaster_valdemaqueda, 
                    group = "P. pinaster",
                    label = ~numero, 
                    icon = ~ colores_parcela[status]) |> 
  addAwesomeMarkers(data = pinea_valdemaqueda, 
                    group = "P. pinea",
                    label = ~numero, 
                    icon = ~ colores_parcela[status]) |> 
   addLayersControl(
    position = "bottomright",
    baseGroups = c("Basemap", "PNOA Máxima Actualidad", 
                  "Interministerial 1973 - 1986", "Vuelo Americano (Serie B, 1956-1957)"),
    overlayGroups = c("P. pinaster","P. pinea","Climate Stations", "Valsain", "MOD13Q Grid", "Landsat Grid", "Sentinel Grid"), 
    options = layersControlOptions(collapsed = TRUE)
  ) |> 
  hideGroup("Landsat Grid") |> 
  hideGroup("Sentinel Grid") |> 
  hideGroup("MOD13Q Grid")
  
```




